# Generated by Django 3.1.3 on 2021-06-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(blank=True, null=True)),
                ('post_count', models.PositiveIntegerField(blank=True, null=True)),
                ('total_view_count', models.PositiveIntegerField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_conf', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('subject_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ingroup_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('source_identifier', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('source_type', models.CharField(blank=True, max_length=200, null=True)),
                ('domain', models.CharField(blank=True, max_length=200, null=True)),
                ('banned', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('hadith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape.hadith')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_language', models.CharField(blank=True, max_length=200, null=True)),
                ('translation_text', models.TextField(blank=True, null=True)),
                ('hadith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape.hadith')),
            ],
        ),
        migrations.CreateModel(
            name='HadithTeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape.hadith')),
                ('teller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape.teller')),
            ],
        ),
        migrations.CreateModel(
            name='HadithReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('hadith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape.hadith')),
            ],
        ),
        migrations.CreateModel(
            name='HadithExplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('hadith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape.hadith')),
            ],
        ),
    ]
