# Generated by Django 3.1.3 on 2021-07-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tellername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('teller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape.teller')),
            ],
        ),
    ]
