# Generated by Django 3.1.3 on 2021-08-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_tellername_hadith'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TranslationReference',
            new_name='HadithExplanationReference',
        ),
        migrations.RenameModel(
            old_name='Translation',
            new_name='HadithTranslation',
        ),
        migrations.RenameModel(
            old_name='HadithExplain',
            new_name='HadithTranslationReference',
        ),
        migrations.RenameField(
            model_name='hadith',
            old_name='ingroup_by_id',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='hadithtranslation',
            old_name='translation_language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='hadithtranslation',
            old_name='translation_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='hadith',
            name='subject_id',
        ),
        migrations.CreateModel(
            name='HadithExplanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('hadith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape.hadith')),
            ],
        ),
    ]
