# Generated by Django 3.1.3 on 2021-08-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_auto_20210815_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hadithexplanationreference',
            old_name='name',
            new_name='maintitle',
        ),
        migrations.RenameField(
            model_name='hadithtranslationreference',
            old_name='name',
            new_name='maintitle',
        ),
        migrations.RemoveField(
            model_name='hadithexplanationreference',
            name='text',
        ),
        migrations.RemoveField(
            model_name='hadithtranslationreference',
            name='text',
        ),
        migrations.AddField(
            model_name='hadithexplanation',
            name='textwithoutformat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hadithtranslation',
            name='textwithoutformat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hadithtranslationreference',
            name='shorttitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
