# Generated by Django 3.1.3 on 2021-08-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0005_auto_20210816_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='teller',
            name='order',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teller',
            name='qael_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teller',
            name='qaelroleid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
